-- =============================================================================
-- SETU SAHAYATA — SEED 16 GOVERNMENT SCHEMES DATA
-- Target Project: https://pvwrwjggazjaktzzqipc.supabase.co
-- Run this script in the Supabase SQL Editor:
-- https://supabase.com/dashboard/project/pvwrwjggazjaktzzqipc/sql/new
-- =============================================================================

INSERT INTO public.schemes (
  id, name, name_hindi, ministry, ministry_hindi, benefit, benefit_hindi, benefit_amount,
  time_to_apply, time_to_apply_hindi, description, description_hindi, category, icon,
  eligibility_tags, eligibility_rules, active, updated_at
) VALUES
(
  'pm-svanidhi',
  'PM SVANidhi',
  'पीएम स्वनिधि',
  'Ministry of Housing & Urban Affairs',
  'आवास और शहरी मामलों के मंत्रालय',
  'Collateral-free working capital loan up to ₹10,000',
  'बिना गारंटी कार्यशील पूंजी ऋण ₹10,000 तक',
  '₹10,000',
  '5 minutes',
  '5 मिनट',
  'A micro-credit scheme for street vendors to restart their businesses after the pandemic.',
  'सड़क विक्रेताओं के लिए एक सूक्ष्म-क्रेडिट योजना।',
  'Finance',
  'Store',
  ARRAY['Street Vendor', 'Udyam Certificate', 'Urban Area'],
  '[{"field":"income","op":"lte","value":200000,"label":"Annual income ≤ ₹2,00,000","labelHindi":"वार्षिक आय ≤ ₹2,00,000"},{"field":"has_aadhaar","op":"is_true","value":true,"label":"Has Aadhaar card","labelHindi":"आधार कार्ड है"},{"field":"occupation","op":"contains","value":"vendor","label":"Occupation is street vendor / vendor","labelHindi":"व्यवसाय: सड़क विक्रेता / विक्रेता"}]'::jsonb,
  true,
  now()
),
(
  'mudra-yojana',
  'Pradhan Mantri Mudra Yojana',
  'प्रधानमंत्री मुद्रा योजना',
  'Ministry of Finance',
  'वित्त मंत्रालय',
  'Business loan up to ₹10,00,000 without collateral',
  'बिना गारंटी व्यापार ऋण ₹10,00,000 तक',
  '₹10,00,000',
  '15 minutes',
  '15 मिनट',
  'Provides loans to small and micro enterprises in three categories — Shishu, Kishore, and Tarun.',
  'छोटे और सूक्ष्म उद्यमों को तीन श्रेणियों में ऋण प्रदान करता है।',
  'Finance',
  'Landmark',
  ARRAY['Small Business', 'Income < ₹8L', 'Non-farm'],
  '[{"field":"income","op":"lte","value":800000,"label":"Annual income ≤ ₹8,00,000","labelHindi":"वार्षिक आय ≤ ₹8,00,000"},{"field":"has_aadhaar","op":"is_true","value":true,"label":"Has Aadhaar card","labelHindi":"आधार कार्ड है"},{"field":"occupation","op":"contains","value":"business","label":"Occupation is business / self-employed","labelHindi":"व्यवसाय: व्यापार / स्व-रोजगार"}]'::jsonb,
  true,
  now()
),
(
  'ayushman-bharat',
  'Ayushman Bharat (PM-JAY)',
  'आयुष्मान भारत (पीएम-जय)',
  'Ministry of Health & Family Welfare',
  'स्वास्थ्य और परिवार कल्याण मंत्रालय',
  'Health insurance cover of ₹5,00,000 per family per year',
  'प्रति परिवार प्रति वर्ष ₹5,00,000 का स्वास्थ्य बीमा',
  '₹5,00,000',
  '10 minutes',
  '10 मिनट',
  'Healthcare program providing a health cover of ₹5 lakh per family per year.',
  'विश्व का सबसे बड़ा सरकारी स्वास्थ्य देखभाल कार्यक्रम।',
  'Health',
  'HeartPulse',
  ARRAY['Low Income', 'Ration Card', 'Family Coverage'],
  '[{"field":"income","op":"lte","value":500000,"label":"Annual income ≤ ₹5,00,000","labelHindi":"वार्षिक आय ≤ ₹5,00,000"},{"field":"has_ration_card","op":"is_true","value":true,"label":"Has ration card","labelHindi":"राशन कार्ड है"}]'::jsonb,
  true,
  now()
),
(
  'pmay',
  'Pradhan Mantri Awas Yojana',
  'प्रधानमंत्री आवास योजना',
  'Ministry of Housing & Urban Affairs',
  'आवास और शहरी मामलों के मंत्रालय',
  'Interest subsidy on home loans up to ₹2.67 lakh',
  'गृह ऋण पर ₹2.67 लाख तक ब्याज सब्सिडी',
  '₹2.67 L',
  '20 minutes',
  '20 मिनट',
  'Provides interest subsidies on home loans to families belonging to EWS, LIG, and MIG.',
  'गृह ऋण पर ब्याज सब्सिडी प्रदान करता है।',
  'Housing',
  'Home',
  ARRAY['No pucca house', 'Income < ₹6L', 'Family'],
  '[{"field":"income","op":"lte","value":600000,"label":"Annual income ≤ ₹6,00,000","labelHindi":"वार्षिक आय ≤ ₹6,00,000"},{"field":"has_aadhaar","op":"is_true","value":true,"label":"Has Aadhaar card","labelHindi":"आधार कार्ड है"}]'::jsonb,
  true,
  now()
),
(
  'sukanya-samriddhi',
  'Sukanya Samriddhi Yojana',
  'सुकन्या समृद्धि योजना',
  'Ministry of Finance',
  'वित्त मंत्रालय',
  'Savings account with 8.2% interest for girl child',
  'बालिका के लिए 8.2% ब्याज दर का बचत खाता',
  '8.2% p.a.',
  '8 minutes',
  '8 मिनट',
  'A small savings scheme for the girl child offering high interest rate.',
  'बालिका के लिए एक छोटी बचत योजना।',
  'Women',
  'GraduationCap',
  ARRAY['Girl Child', 'Age < 10', 'Savings'],
  '[{"field":"gender","op":"eq","value":"Female","label":"Applicant is female","labelHindi":"आवेदक महिला है"},{"field":"has_aadhaar","op":"is_true","value":true,"label":"Has Aadhaar card","labelHindi":"आधार कार्ड है"}]'::jsonb,
  true,
  now()
),
(
  'anna-yojana',
  'Antyodaya Anna Yojana',
  'अंत्योदय अन्न योजना',
  'Ministry of Consumer Affairs',
  'उपभोक्ता मामलों के मंत्रालय',
  '35 kg food grains at subsidized rates per month',
  'प्रति माह 35 किग्रा अनाज सब्सिडी दर पर',
  '35 kg/mo',
  '7 minutes',
  '7 मिनट',
  'Targeted at the poorest of poor families, providing 35 kg of food grains per month.',
  'सबसे गरीब परिवारों के लिए प्रति माह 35 किग्रा अनाज।',
  'Food',
  'Wheat',
  ARRAY['BPL Card', 'Ration Card', 'Lowest Income'],
  '[{"field":"income","op":"lte","value":100000,"label":"Annual income ≤ ₹1,00,000","labelHindi":"वार्षिक आय ≤ ₹1,00,000"},{"field":"has_ration_card","op":"is_true","value":true,"label":"Has ration card","labelHindi":"राशन कार्ड है"}]'::jsonb,
  true,
  now()
),
(
  'pm-kisan',
  'PM Kisan Samman Nidhi',
  'पीएम किसान सम्मान निधि',
  'Ministry of Agriculture & Farmers Welfare',
  'कृषि एवं किसान कल्याण मंत्रालय',
  '₹6,000 per year direct income support in 3 equal installments',
  '3 समान किस्तों में प्रति वर्ष ₹6,000 सीधी आय सहायता',
  '₹6,000/yr',
  '10 minutes',
  '10 मिनट',
  'Direct income support of ₹6,000 per annum transferred into bank accounts of land-holding farmer families.',
  'किसान परिवारों के बैंक खातों में सीधी आय सहायता।',
  'Finance',
  'Wheat',
  ARRAY['Farmer', 'Aadhaar Linked', 'Landholder'],
  '[{"field":"has_aadhaar","op":"is_true","value":true,"label":"Has Aadhaar card","labelHindi":"आधार कार्ड है"},{"field":"occupation","op":"contains","value":"farmer","label":"Occupation is farmer / landholder","labelHindi":"व्यवसाय: किसान / भूमिधारक"}]'::jsonb,
  true,
  now()
),
(
  'pmkvy',
  'Pradhan Mantri Kaushal Vikas Yojana',
  'प्रधानमंत्री कौशल विकास योजना',
  'Ministry of Skill Development & Entrepreneurship',
  'कौशल विकास और उद्यमिता मंत्रालय',
  'Free industry-relevant skill training & skill certification',
  'निःशुल्क उद्योग-प्रासंगिक कौशल प्रशिक्षण और प्रमाणन',
  'Free Training',
  '12 minutes',
  '12 मिनट',
  'Flagship skill certification scheme enabling Indian youth to take up skill training.',
  'भारतीय युवाओं को कौशल प्रशिक्षण लेने में सक्षम बनाने वाली प्रमुख योजना।',
  'Education',
  'GraduationCap',
  ARRAY['Youth', 'Skill Training', 'Free Certification'],
  '[{"field":"has_aadhaar","op":"is_true","value":true,"label":"Has Aadhaar card","labelHindi":"आधार कार्ड है"}]'::jsonb,
  true,
  now()
),
(
  'ujjwala-yojana',
  'Pradhan Mantri Ujjwala Yojana',
  'प्रधानमंत्री उज्जवला योजना',
  'Ministry of Petroleum & Natural Gas',
  'पेट्रोलियम एवं प्राकृतिक गैस मंत्रालय',
  'Deposit-free LPG connection & financial assistance of ₹1,600',
  'डिपॉजिट-फ्री एलपीजी कनेक्शन और ₹1,600 की वित्तीय सहायता',
  'Free LPG Connection',
  '15 minutes',
  '15 मिनट',
  'Provides deposit-free LPG connections to women belonging to below poverty line (BPL) households.',
  'गरीबी रेखा से नीचे की महिलाओं को डिपॉजिट-फ्री एलपीजी कनेक्शन।',
  'Women',
  'Home',
  ARRAY['Women', 'BPL Household', 'Aadhaar Required'],
  '[{"field":"gender","op":"eq","value":"Female","label":"Applicant is female","labelHindi":"आवेदक महिला है"},{"field":"income","op":"lte","value":180000,"label":"Annual income ≤ ₹1,80,000 (BPL)","labelHindi":"वार्षिक आय ≤ ₹1,80,000 (बीपीएल)"}]'::jsonb,
  true,
  now()
),
(
  'pmjjby',
  'Pradhan Mantri Jeevan Jyoti Bima Yojana',
  'प्रधानमंत्री जीवन ज्योति बीमा योजना',
  'Ministry of Finance',
  'वित्त मंत्रालय',
  'Life insurance cover of ₹2,00,000 for ₹436 per annum',
  '₹436 प्रति वर्ष प्रीमियम पर ₹2,00,000 का जीवन बीमा',
  '₹2,00,000',
  '5 minutes',
  '5 मिनट',
  'Renewable one-year term life insurance scheme providing ₹2 lakh life cover.',
  'एक वर्षीय जीवन बीमा योजना जो ₹2 लाख का जीवन कवर प्रदान करती है।',
  'Finance',
  'Landmark',
  ARRAY['Age 18-50', 'Bank Account', 'Low Premium'],
  '[{"field":"has_aadhaar","op":"is_true","value":true,"label":"Has Aadhaar card","labelHindi":"आधार कार्ड है"}]'::jsonb,
  true,
  now()
),
(
  'pmsby',
  'Pradhan Mantri Suraksha Bima Yojana',
  'प्रधानमंत्री सुरक्षा बीमा योजना',
  'Ministry of Finance',
  'वित्त मंत्रालय',
  'Accidental death & disability cover up to ₹2,00,000 for ₹20/year',
  '₹20/वर्ष प्रीमियम पर ₹2,00,000 तक दुर्घटना और विकलांगता बीमा',
  '₹2,00,000',
  '5 minutes',
  '5 मिनट',
  'Accident insurance scheme offering accidental death and disability coverage.',
  'मात्र ₹20 प्रति वर्ष में दुर्घटना और विकलांगता कवर।',
  'Health',
  'HeartPulse',
  ARRAY['Age 18-70', 'Bank Account', 'Micro Insurance'],
  '[{"field":"has_aadhaar","op":"is_true","value":true,"label":"Has Aadhaar card","labelHindi":"आधार कार्ड है"}]'::jsonb,
  true,
  now()
),
(
  'apy',
  'Atal Pension Yojana',
  'अटल पेंशन योजना',
  'Ministry of Finance',
  'वित्त मंत्रालय',
  'Guaranteed minimum monthly pension of ₹1,000 to ₹5,000 after age 60',
  '60 वर्ष की आयु के बाद ₹1,000 से ₹5,000 की न्यूनतम मासिक पेंशन',
  'Up to ₹5,000/mo',
  '10 minutes',
  '10 मिनट',
  'Government-backed pension scheme targeted at unorganized sector workers.',
  'असंगठित क्षेत्र के श्रमिकों के लिए सरकार द्वारा समर्थित पेंशन योजना।',
  'Finance',
  'Landmark',
  ARRAY['Unorganized Worker', 'Age 18-40', 'Pension'],
  '[{"field":"has_aadhaar","op":"is_true","value":true,"label":"Has Aadhaar card","labelHindi":"आधार कार्ड है"}]'::jsonb,
  true,
  now()
),
(
  'nsp-scholarship',
  'National Scholarship Portal Scheme',
  'राष्ट्रीय छात्रवृत्ति पोर्टल योजना',
  'Ministry of Education',
  'शिक्षा मंत्रालय',
  'Financial assistance for pre-matric & post-matric students',
  'प्री-मैट्रिक और पोस्ट-मैट्रिक छात्रों के लिए वित्तीय सहायता',
  'Up to ₹20,000/yr',
  '15 minutes',
  '15 मिनट',
  'Single window scholarship portal offering financial support to SC, ST, OBC, and EWS students.',
  'छात्रों को वित्तीय सहायता देने वाला एकल विंडो छात्रवृत्ति पोर्टल।',
  'Education',
  'GraduationCap',
  ARRAY['Students', 'SC/ST/OBC', 'Income < ₹2.5L'],
  '[{"field":"income","op":"lte","value":250000,"label":"Annual family income ≤ ₹2,50,000","labelHindi":"वार्षिक पारिवारिक आय ≤ ₹2,50,000"}]'::jsonb,
  true,
  now()
),
(
  'pm-poshan',
  'PM POSHAN Scheme',
  'पीएम पोषण योजना',
  'Ministry of Education',
  'शिक्षा मंत्रालय',
  'Free nutritious mid-day meals for school children in Class I to VIII',
  'कक्षा I से VIII तक के स्कूली बच्चों के लिए निःशुल्क पौष्टिक भोजन',
  'Free Meals',
  '5 minutes',
  '5 मिनट',
  'National scheme providing hot cooked meals to school children.',
  'स्कूली बच्चों को गर्म पका हुआ भोजन प्रदान करने वाली राष्ट्रीय योजना।',
  'Food',
  'Wheat',
  ARRAY['School Children', 'Nutrition', 'Free Meal'],
  '[{"field":"has_ration_card","op":"is_true","value":true,"label":"Has ration card","labelHindi":"राशन कार्ड है"}]'::jsonb,
  true,
  now()
),
(
  'sbm-gramin',
  'Swachh Bharat Mission Gramin',
  'स्वच्छ भारत मिशन ग्रामीण',
  'Ministry of Jal Shakti',
  'जल शक्ति मंत्रालय',
  'Incentive of ₹12,000 for construction of Individual Household Latrine',
  'व्यक्तिगत घरेलू शौचालय के निर्माण के लिए ₹12,000 का प्रोत्साहन',
  '₹12,000',
  '10 minutes',
  '10 मिनट',
  'Provides financial support of ₹12,000 to rural households for constructing toilets.',
  'ग्रामीण BPL और पात्र APL परिवारों को शौचालय बनाने के लिए ₹12,000।',
  'Housing',
  'Home',
  ARRAY['Rural Household', 'No Toilet', 'BPL/APL'],
  '[{"field":"has_ration_card","op":"is_true","value":true,"label":"Has ration card","labelHindi":"राशन कार्ड है"}]'::jsonb,
  true,
  now()
),
(
  'stand-up-india',
  'Stand-Up India Scheme',
  'स्टैंड-अप इंडिया योजना',
  'Ministry of Finance',
  'वित्त मंत्रालय',
  'Bank loan between ₹10 lakh to ₹1 crore for SC/ST and Women entrepreneurs',
  'SC/ST और महिला उद्यमियों के लिए ₹10 लाख से ₹1 करोड़ तक बैंक ऋण',
  'Up to ₹1 Crore',
  '20 minutes',
  '20 मिनट',
  'Facilitates bank loans to SC/ST and women borrowers for greenfield enterprises.',
  'ग्रीनफील्ड उद्यम स्थापित करने के लिए SC/ST और महिला उद्यमियों को ऋण।',
  'Women',
  'Landmark',
  ARRAY['SC/ST', 'Women Entrepreneur', 'Greenfield Enterprise'],
  '[{"field":"gender","op":"eq","value":"Female","label":"Applicant is female","labelHindi":"आवेदक महिला है"}]'::jsonb,
  true,
  now()
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_hindi = EXCLUDED.name_hindi,
  ministry = EXCLUDED.ministry,
  ministry_hindi = EXCLUDED.ministry_hindi,
  benefit = EXCLUDED.benefit,
  benefit_hindi = EXCLUDED.benefit_hindi,
  benefit_amount = EXCLUDED.benefit_amount,
  time_to_apply = EXCLUDED.time_to_apply,
  time_to_apply_hindi = EXCLUDED.time_to_apply_hindi,
  description = EXCLUDED.description,
  description_hindi = EXCLUDED.description_hindi,
  category = EXCLUDED.category,
  icon = EXCLUDED.icon,
  eligibility_tags = EXCLUDED.eligibility_tags,
  eligibility_rules = EXCLUDED.eligibility_rules,
  active = EXCLUDED.active,
  updated_at = now();
