import type {
  UserProfile,
  Scheme,
  AssistanceCenter,
  JargonDocument,
  ApplicationField,
} from './types';

export const mockUserProfile: UserProfile = {
  name: 'Priya',
  nameHindi: 'प्रिया',
  age: 28,
  gender: 'Female',
  city: 'Lucknow',
  state: 'Uttar Pradesh',
  income: 180000,
  category: 'OBC',
  occupation: 'Small Business Owner (Street Vendor)',
  hasAadhaar: true,
  hasRationCard: true,
  hasUdyam: true,
  familySize: 4,
};

export const mockSchemes: Scheme[] = [
  {
    id: 'pm-svanidhi',
    name: 'PM SVANidhi',
    nameHindi: 'पीएम स्वनिधि',
    ministry: 'Ministry of Housing & Urban Affairs',
    ministryHindi: 'आवास और शहरी मामलों के मंत्रालय',
    benefit: 'Collateral-free working capital loan up to ₹10,000',
    benefitHindi: 'बिना गारंटी कार्यशील पूंजी ऋण ₹10,000 तक',
    benefitAmount: '₹10,000',
    matchPercent: 96,
    timeToApply: '5 minutes',
    timeToApplyHindi: '5 मिनट',
    description:
      'A micro-credit scheme for street vendors to restart their businesses after the pandemic. Eligible vendors receive an initial working capital loan that can be repaid in monthly installments.',
    descriptionHindi:
      'सड़क विक्रेताओं के लिए एक सूक्ष्म-क्रेडिट योजना जो उन्हें अपना व्यवसाय फिर से शुरू करने में मदद करती है। पात्र विक्रेताओं को कार्यशील पूंजी ऋण मिलता है जिसे मासिक किस्तों में चुकाया जा सकता है।',
    category: 'Finance',
    icon: 'Store',
    eligibilityTags: ['Street Vendor', 'Udyam Certificate', 'Urban Area'],
  },
  {
    id: 'mudra-yojana',
    name: 'Pradhan Mantri Mudra Yojana',
    nameHindi: 'प्रधानमंत्री मुद्रा योजना',
    ministry: 'Ministry of Finance',
    ministryHindi: 'वित्त मंत्रालय',
    benefit: 'Business loan up to ₹10,00,000 without collateral',
    benefitHindi: 'बिना गारंटी व्यापार ऋण ₹10,00,000 तक',
    benefitAmount: '₹10,00,000',
    matchPercent: 89,
    timeToApply: '15 minutes',
    timeToApplyHindi: '15 मिनट',
    description:
      'Provides loans to small and micro enterprises in three categories — Shishu (up to ₹50,000), Kishore (up to ₹5,00,000), and Tarun (up to ₹10,00,000). No collateral required for loans up to ₹10 lakh.',
    descriptionHindi:
      'छोटे और सूक्ष्म उद्यमों को तीन श्रेणियों में ऋण प्रदान करता है — शिशु (₹50,000 तक), किशोर (₹5,00,000 तक), और तरुण (₹10,00,000 तक)। ₹10 लाख तक के ऋण पर कोई गारंटी आवश्यक नहीं।',
    category: 'Finance',
    icon: 'Landmark',
    eligibilityTags: ['Small Business', 'Income < ₹8L', 'Non-farm'],
  },
  {
    id: 'ayushman-bharat',
    name: 'Ayushman Bharat (PM-JAY)',
    nameHindi: 'आयुष्मान भारत (पीएम-जय)',
    ministry: 'Ministry of Health & Family Welfare',
    ministryHindi: 'स्वास्थ्य और परिवार कल्याण मंत्रालय',
    benefit: 'Health insurance cover of ₹5,00,000 per family per year',
    benefitHindi: 'प्रति परिवार प्रति वर्ष ₹5,00,000 का स्वास्थ्य बीमा',
    benefitAmount: '₹5,00,000',
    matchPercent: 84,
    timeToApply: '10 minutes',
    timeToApplyHindi: '10 मिनट',
    description:
      'The world\'s largest government-funded healthcare program providing a health cover of ₹5 lakh per family per year for secondary and tertiary care hospitalization.',
    descriptionHindi:
      'विश्व का सबसे बड़ा सरकारी स्वास्थ्य देखभाल कार्यक्रम जो माध्यमिक और तृतीयक अस्पताल में भर्ती के लिए प्रति परिवार प्रति वर्ष ₹5 लाख का स्वास्थ्य कवर प्रदान करता है।',
    category: 'Health',
    icon: 'HeartPulse',
    eligibilityTags: ['Low Income', 'Ration Card', 'Family Coverage'],
  },
  {
    id: 'pmay',
    name: 'Pradhan Mantri Awas Yojana',
    nameHindi: 'प्रधानमंत्री आवास योजना',
    ministry: 'Ministry of Housing & Urban Affairs',
    ministryHindi: 'आवास और शहरी मामलों के मंत्रालय',
    benefit: 'Interest subsidy on home loans up to ₹2.67 lakh',
    benefitHindi: 'गृह ऋण पर ₹2.67 लाख तक ब्याज सब्सिडी',
    benefitAmount: '₹2.67 L',
    matchPercent: 78,
    timeToApply: '20 minutes',
    timeToApplyHindi: '20 मिनट',
    description:
      'Provides interest subsidies on home loans to families belonging to EWS, LIG, and MIG categories. Beneficiaries can get subsidies ranging from ₹1 lakh to ₹2.67 lakh depending on income category.',
    descriptionHindi:
      'EWS, LIG, और MIG श्रेणियों के परिवारों को गृह ऋण पर ब्याज सब्सिडी प्रदान करता है। आय श्रेणी के आधार पर लाभार्थियों को ₹1 लाख से ₹2.67 लाख तक की सब्सिडी मिल सकती है।',
    category: 'Housing',
    icon: 'Home',
    eligibilityTags: ['No pucca house', 'Income < ₹6L', 'Family'],
  },
  {
    id: 'sukanya-samriddhi',
    name: 'Sukanya Samriddhi Yojana',
    nameHindi: 'सुकन्या समृद्धि योजना',
    ministry: 'Ministry of Finance',
    ministryHindi: 'वित्त मंत्रालय',
    benefit: 'Savings account with 8.2% interest for girl child',
    benefitHindi: 'बालिका के लिए 8.2% ब्याज दर का बचत खाता',
    benefitAmount: '8.2% p.a.',
    matchPercent: 72,
    timeToApply: '8 minutes',
    timeToApplyHindi: '8 मिनट',
    description:
      'A small savings scheme for the girl child offering one of the highest interest rates among all small savings schemes. Account can be opened for a girl child up to 10 years of age.',
    descriptionHindi:
      'बालिका के लिए एक छोटी बचत योजना जो सभी छोटी बचत योजनाओं में सबसे उच्च ब्याज दरों में से एक प्रदान करती है। 10 वर्ष तक की बालिका के लिए खाता खोला जा सकता है।',
    category: 'Women',
    icon: 'GraduationCap',
    eligibilityTags: ['Girl Child', 'Age < 10', 'Savings'],
  },
  {
    id: 'anna-yojana',
    name: 'Antyodaya Anna Yojana',
    nameHindi: 'अंत्योदय अन्न योजना',
    ministry: 'Ministry of Consumer Affairs',
    ministryHindi: 'उपभोक्ता मामलों के मंत्रालय',
    benefit: '35 kg food grains at subsidized rates per month',
    benefitHindi: 'प्रति माह 35 किग्रा अनाज सब्सिडी दर पर',
    benefitAmount: '35 kg/mo',
    matchPercent: 68,
    timeToApply: '7 minutes',
    timeToApplyHindi: '7 मिनट',
    description:
      'Targeted at the poorest of poor families, providing 35 kg of food grains (rice at ₹3/kg, wheat at ₹2/kg) per family per month at highly subsidized prices.',
    descriptionHindi:
      'सबसे गरीब परिवारों के लिए, प्रति परिवार प्रति माह 35 किग्रा अनाज (₹3/किग्रा चावल, ₹2/किग्रा गेहूं) अत्यधिक सब्सिडी दर पर प्रदान करता है।',
    category: 'Food',
    icon: 'Wheat',
    eligibilityTags: ['BPL Card', 'Ration Card', 'Lowest Income'],
  },
];

export const mockAssistanceCenters: AssistanceCenter[] = [
  {
    name: 'Jan Seva Kendra — Gomti Nagar',
    nameHindi: 'जन सेवा केंद्र — गोमती नगर',
    address: 'Vikas Bhawan, Gomti Nagar, Lucknow, UP 226010',
    addressHindi: 'विकास भवन, गोमती नगर, लखनऊ, उप्र 226010',
    distance: '1.2 km',
    hours: 'Mon–Sat, 9 AM – 5 PM',
    hoursHindi: 'सोम–शनि, सुबह 9 – शाम 5',
    phone: '+91 522 223 4567',
  },
  {
    name: 'CSC Common Service Center — Hazratganj',
    nameHindi: 'सीएससी सामान्य सेवा केंद्र — हजरतगंज',
    address: '10, Shahnajaf Road, Hazratganj, Lucknow, UP 226001',
    addressHindi: '10, शाहनजफ रोड, हजरतगंज, लखनऊ, उप्र 226001',
    distance: '2.8 km',
    hours: 'Mon–Sun, 8 AM – 8 PM',
    hoursHindi: 'सोम–रवि, सुबह 8 – रात 8',
    phone: '+91 522 415 8900',
  },
  {
    name: 'District Magistrate Office Help Desk',
    nameHindi: 'जिलाधिकारी कार्यालय सहायता डेस्क',
    address: 'Collectorate, Hazratganj, Lucknow, UP 226001',
    addressHindi: 'कलेक्ट्रेट, हजरतगंज, लखनऊ, उप्र 226001',
    distance: '3.1 km',
    hours: 'Mon–Fri, 10 AM – 4 PM',
    hoursHindi: 'सोम–शुक्र, सुबह 10 – शाम 4',
    phone: '+91 522 262 6777',
  },
];

export const mockJargonDocument: JargonDocument = {
  id: 'svanidhi-circular',
  title: 'PM SVANidhi Scheme — Revised Operational Guidelines (2024)',
  titleHindi: 'पीएम स्वनिधि योजना — संशोधित परिचालन दिशानिर्देश (2024)',
  source: 'Ministry of Housing & Urban Affairs',
  sourceHindi: 'आवास और शहरी मामलों के मंत्रालय',
  legalText: [
    'In exercise of the powers conferred by sub-section (2) of section 3 of the PM SVANidhi Scheme, the Central Government hereby notifies the following revised operational guidelines for implementation of the PM Street Vendor\'s AtmaNirbhar Nidhi (PM SVANidhi) Scheme.',
    'Eligibility Criteria: (a) The applicant must be a street vendor as defined under Section 2(1)(t) of the Street Vendors (Protection of Livelihood and Regulation of Street Vending) Act, 2014, and (b) must possess a valid Certificate of Vending (CoV) or Letter of Recommendation (LoR) issued by the Urban Local Body (ULB) concerned, and (c) the annual turnover of the vending enterprise shall not exceed ₹2,00,000 (Rupees Two Lakhs only) per annum.',
    ' quantum of Working Capital Loan: The initial working capital loan shall be sanctioned for an amount not exceeding ₹10,000 (Rupees Ten Thousand only) per beneficiary, repayable in 24 monthly installments, with a moratorium of 3 (three) months from the date of disbursement. Upon successful repayment, the beneficiary shall be eligible for a subsequent tranche of ₹20,000, and thereafter ₹50,000 under the scheme\'s progressive credit enhancement framework.',
    'Rate of Interest: The rate of interest payable on the working capital loan shall be 7% (seven percent) per annum flat. However, an interest subsidy of 7% (seven percent) per annum shall be provided to the beneficiaries upon timely repayment, effectively rendering the loan interest-free, subject to timely repayment as defined under Clause 4.3.2 of these Guidelines.',
    'Non-Performing Asset (NPA) Classification: The loan shall be classified as a Non-Performing Asset if the borrower fails to remit the stipulated installment for a period exceeding 90 (ninety) consecutive days from the due date. In the event of NPA classification, the interest subsidy benefits shall stand forfeited prospectively, and the outstanding principal shall accrue interest at the prevailing MCLR of the lending institution plus 2% (two percent).',
  ],
  legalTextHindi: [
    'पीएम स्वनिधि योजना की धारा 3 की उप-धारा (2) द्वारा प्रदत्त शक्तियों का प्रयोग करते हुए, केंद्र सरकार एतद्द्वारा पीएम स्ट्रीट वेंडर\'स आत्मनिर्भर निधि (पीएम स्वनिधि) योजना के क्रियान्वयन हेतु निम्नलिखित संशोधित परिचालन दिशानिर्देश अधिसूचित करती है।',
    'पात्रता मानदंड: (क) आवेदक स्ट्रीट वेंडर्स (संरक्षण और विनियमन) अधिनियम, 2014 की धारा 2(1)(ट) के अंतर्गत परिभाषित सड़क विक्रेता होना चाहिए, (ख) संबंधित नगरीय स्थानीय निकाय (ULB) द्वारा जारी वैध वेंडिंग प्रमाणपत्र (CoV) या सिफारिश पत्र (LoR) रखना चाहिए, (ग) वेंडिंग उद्यम की वार्षिक आवक्ति ₹2,00,000 प्रति वर्ष से अधिक नहीं होनी चाहिए।',
    'कार्यशील पूंजी ऋण का क्वांटम: प्रारंभिक कार्यशील पूंजी ऋण ₹10,000 प्रति लाभार्थी तक स्वीकृत किया जाएगा, जो 24 मासिक किस्तों में चुकाने योग्य होगा, वितरण की तिथि से 3 महीने की छूट के साथ। सफल चुकौती पर, लाभार्थी ₹20,000 की अगली किस्त के लिए पात्र होगा, और तदुपरांत ₹50,000 के लिए।',
    'ब्याज दर: कार्यशील पूंजी ऋण पर देय ब्याज दर 7% प्रति वर्ष फ्लैट होगी। हालांकि, समय पर चुकौती पर 7% प्रति वर्ष की ब्याज सब्सिडी प्रदान की जाएगी, जिससे ऋण प्रभावी रूप से ब्याज-मुक्त हो जाएगा।',
    'एनपीए वर्गीकरण: यदि उधारकर्ता नियत तिथि से 90 लगातार दिनों तक किस्त जमा करने में विफल रहता है तो ऋण को नॉन-परफॉर्मिंग एसेट के रूप में वर्गीकृत किया जाएगा। एनपीए वर्गीकरण की स्थिति में, ब्याज सब्सिडी लाभ भविष्य के लिए समाप्त हो जाएंगे।',
  ],
  summary: [
    'This scheme gives you a loan of up to ₹10,000 to run your small business — and if you pay it back on time, there is NO interest (it is essentially a free loan).',
    'To qualify, you must be a street vendor with a valid vendor certificate (or a recommendation letter from your local municipal office), earning less than ₹2 lakh per year.',
    'If you repay on time, you can get a second loan of ₹20,000, and then a third of ₹50,000 — growing your business step by step.',
  ],
  summaryHindi: [
    'यह योजना आपको छोटा व्यवसाय चलाने के लिए ₹10,000 तक का ऋण देती है — और यदि आप समय पर चुकाते हैं, तो कोई ब्याज नहीं है (यह लगभग मुफ्त ऋण है)।',
    'पात्र होने के लिए, आपको वैध वेंडर प्रमाणपत्र (या नगर पालिका कार्यालय से सिफारिश पत्र) के साथ सड़क विक्रेता होना चाहिए, जिसकी वार्षिक आय ₹2 लाख से कम हो।',
    'यदि आप समय पर चुकाते हैं, तो आप ₹20,000 का दूसरा ऋण, और फिर ₹50,000 का तीसरा ऋण पा सकते हैं — अपना व्यवसाय चरण-दर-चरण बढ़ाते हुए।',
  ],
  nextSteps: [
    'Gather your vendor certificate (or get a recommendation letter from your local municipal office).',
    'Take your Aadhaar card and one passport-size photo to a nearby bank or assistance center.',
    'Fill out the application — our AI assistant can auto-fill it from your documents.',
    'Receive your loan within 7–10 working days in your bank account.',
  ],
  nextStepsHindi: [
    'अपना वेंडर प्रमाणपत्र इकट्ठा करें (या नगर पालिका कार्यालय से सिफारिश पत्र प्राप्त करें)।',
    'अपना आधार कार्ड और एक पासपोर्ट-साइज़ फोटो नजदीकी बैंक या सहायता केंद्र में ले जाएं।',
    'आवेदन भरें — हमारी एआई सहायक आपके दस्तावेज़ों से इसे स्वतः भर सकती है।',
    'अपने बैंक खाते में 7–10 कार्य दिवसों के भीतर ऋण प्राप्त करें।',
  ],
};

export const mockApplicationFields: ApplicationField[] = [
  {
    id: 'name',
    label: 'Full Name',
    labelHindi: 'पूरा नाम',
    value: 'Priya Sharma',
    valueHindi: 'प्रिया शर्मा',
    preFilled: true,
    type: 'text',
  },
  {
    id: 'age',
    label: 'Age',
    labelHindi: 'आयु',
    value: '28',
    valueHindi: '28',
    preFilled: true,
    type: 'text',
  },
  {
    id: 'gender',
    label: 'Gender',
    labelHindi: 'लिंग',
    value: 'Female',
    valueHindi: 'महिला',
    preFilled: true,
    type: 'select',
    options: ['Female', 'Male', 'Other'],
  },
  {
    id: 'aadhaar',
    label: 'Aadhaar Number',
    labelHindi: 'आधार नंबर',
    value: 'XXXX-XXXX-7845',
    valueHindi: 'XXXX-XXXX-7845',
    preFilled: true,
    type: 'text',
  },
  {
    id: 'address',
    label: 'Residential Address',
    labelHindi: 'आवासीय पता',
    value: '23, Gomti Nagar, Lucknow, Uttar Pradesh 226010',
    valueHindi: '23, गोमती नगर, लखनऊ, उत्तर प्रदेश 226010',
    preFilled: true,
    type: 'textarea',
  },
  {
    id: 'income',
    label: 'Annual Family Income (₹)',
    labelHindi: 'वार्षिक पारिवारिक आय (₹)',
    value: '1,80,000',
    valueHindi: '1,80,000',
    preFilled: true,
    type: 'text',
  },
  {
    id: 'category',
    label: 'Social Category',
    labelHindi: 'सामाजिक श्रेणी',
    value: 'OBC',
    valueHindi: 'ओबीसी',
    preFilled: true,
    type: 'select',
    options: ['General', 'OBC', 'SC', 'ST'],
  },
  {
    id: 'occupation',
    label: 'Occupation / Business Type',
    labelHindi: 'व्यवसाय / व्यापार का प्रकार',
    value: 'Street Vendor (Fruit & Vegetable)',
    valueHindi: 'सड़क विक्रेता (फल और सब्जी)',
    preFilled: true,
    type: 'text',
  },
  {
    id: 'udyam',
    label: 'Udyam Registration Number',
    labelHindi: 'उद्यम पंजीकरण नंबर',
    value: 'UDYAM-UP-03-0042951',
    valueHindi: 'UDYAM-UP-03-0042951',
    preFilled: true,
    type: 'text',
  },
  {
    id: 'bank',
    label: 'Bank Account Number',
    labelHindi: 'बैंक खाता संख्या',
    value: '',
    valueHindi: '',
    preFilled: false,
    type: 'text',
  },
  {
    id: 'ifsc',
    label: 'IFSC Code',
    labelHindi: 'आईएफएससी कोड',
    value: '',
    valueHindi: '',
    preFilled: false,
    type: 'text',
  },
  {
    id: 'loan-amount',
    label: 'Requested Loan Amount (₹)',
    labelHindi: 'अनुरोधित ऋण राशि (₹)',
    value: '10,000',
    valueHindi: '10,000',
    preFilled: true,
    type: 'text',
  },
  {
    id: 'declaration',
    label: 'Declaration',
    labelHindi: 'घोषणा',
    value: 'I declare that the information provided is true and correct to the best of my knowledge.',
    valueHindi: 'मैं घोषित करता/करती हूं कि दी गई जानकारी मेरी जानकारी के अनुसार सत्य और सही है।',
    preFilled: true,
    type: 'textarea',
  },
];

export const statTickerItems = [
  'Find welfare schemes you may qualify for',
  'Upload documents and get matched in seconds',
  'Plain-language explanations of government jargon',
  'Available in Hindi and English',
  'Auto-fill applications from your profile',
  'Track your submitted applications in one place',
];
